name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Se ejecuta cuando haces push en main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Checkout del repositorio
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        persist-credentials: false

    # Verificar si API_KEY está configurado
    - name: Check if API_KEY exists
      run: |
        if [[ -z "${{ secrets.API_KEY }}" ]]; then
          echo "ERROR: API_KEY está vacío o no está configurado en los Secrets de GitHub."
          exit 1
        else
          echo "API_KEY está configurado correctamente."
        fi

    # Crear archivo de configuración con la API Key
    - name: Create config.js file
      run: |
        mkdir -p js
        echo "const CONFIG = { API_KEY: \"${{ secrets.API_KEY }}\" };" > js/config.js
        cat js/config.js  # Muestra el contenido del archivo en los logs

    # Verificar si config.js se creó correctamente
    - name: List files before deploy
      run: find . -type f

    - name: Force push main to gh-pages   
      run: git push origin main:gh-pages -f

    # Desplegar a GitHub Pages
    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: gh-pages  # Se despliega en la rama gh-pages
        folder: .         # Sube todo el contenido
        clean: false      # Evita que se borren archivos previos
